<a href="https://colab.research.google.com/github/abeeraz379/Logistic-Regression-Optimization-Stroke-data-/blob/main/stroke.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import libraries

In [53]:
# import numpy ,pandas
# import test train split
# import logisticregression
# import Gridsearchcv
# import scaler
# import pipeline
# import onehot encoder
# import simple imbuter
# import confusion matrix , confusion report
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import confusion_matrix,classification_report
import warnings
warnings.filterwarnings('ignore')

# load and inspect data

In [2]:
# load stroke data
df=pd.read_csv("/content/drive/MyDrive/AXSOSACADEMY/AXSOSACADEMY/02-IntroML/Week07/Data/stroke.csv")
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1192,Female,31,0,0,No,Govt_job,Rural,70.66,27.2,never smoked,0
1,77,Female,13,0,0,No,children,Rural,85.81,18.6,Unknown,0
2,59200,Male,18,0,0,No,Private,Urban,60.56,33.0,never smoked,0
3,24905,Female,65,0,0,Yes,Private,Urban,205.77,46.0,formerly smoked,1
4,24257,Male,4,0,0,No,children,Rural,90.42,16.2,Unknown,0

In [3]:
# show info about df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1137 entries, 0 to 1136
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1137 non-null   int64
 1   gender             1137 non-null   object
 2   age                1137 non-null   object
 3   hypertension       1137 non-null   int64
 4   heart_disease      1137 non-null   int64
 5   ever_married       1137 non-null   object
 6   work_type          1137 non-null   object
 7   Residence_type     1137 non-null   object
 8   avg_glucose_level  1137 non-null   float64
 9   bmi                1085 non-null   float64
 10  smoking_status     1137 non-null   object
 11  stroke             1137 non-null   int64
dtypes: float64(2), int64(4), object(6)
memory usage: 106.7+ KB

In [4]:
# show statistical info about df
df.describe()

,id,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,1137.000000,1137.000000,1137.000000,1137.000000,1085.000000,1137.000000
mean,36750.933157,0.118734,0.068602,107.664002,29.198065,0.120493
std,21112.281253,0.323617,0.252887,47.618723,7.669615,0.325680
min,77.000000,0.000000,0.000000,55.270000,11.300000,0.000000
25%,17986.000000,0.000000,0.000000,77.600000,24.100000,0.000000
50%,37479.000000,0.000000,0.000000,91.820000,28.500000,0.000000
75%,55410.000000,0.000000,0.000000,113.850000,33.200000,0.000000
max,72918.000000,1.000000,1.000000,266.590000,64.400000,1.000000

In [5]:
# show statistical info about object features
df.describe(include="object")

        gender   age ever_married work_type Residence_type smoking_status
count     1137  1137         1137      1137           1137           1137
unique       3    84            2         5              2              4
top     Female    79          Yes   Private          Urban   never smoked
freq       642    26          769       672            587            416

In [6]:
# show values of each column
for col in df.columns:
  print(col)
  print(df[col].unique())

id
[ 1192    77 59200 ... 59749 12109  5731]
gender
['Female' 'Male' 'Other']
age
['31' '13' '18' '65' '4' '28' '64' '62' '26' '63' '50' '77' '1' '52' '24'
 '48' '45' '74' '3' '17' '54' '55' '67' '35' '38' '81' '34' '44' '79' '56'
 '70' '30' '39' '29' '80' '59' '51' '19' '43' '71' '0' '23' '53' '78' '66'
 '60' '76' '22' '6' '47' '2' '46' '11' '33' '37' '49' '61' '75' '40' '8'
 '57' '12' '21' '41' '58' '27' '20' '68' '42' '5' '69' '9' '36' '25' '82'
 '73' '32' '7' '16' '14' '72' '15' '10' '*82']
hypertension
[0 1]
heart_disease
[0 1]
ever_married
['No' 'Yes']
work_type
['Govt_job' 'children' 'Private' 'Self-employed' 'Never_worked']
Residence_type
['Rural' 'Urban']
avg_glucose_level
[ 70.66  85.81  60.56 ... 234.35  80.43 108.61]
bmi
[27.2 18.6 33.  46.  16.2 30.3 31.4 31.7 20.3 27.4 34.5 32.8 17.2 32.3
 26.1 32.2 29.4 26.8 21.7 18.3 22.9 20.8 27.  25.6 24.8 27.6 44.6 43.2
 33.2 30.7 37.6 35.5 25.2 31.1 36.  21.4 24.2 26.3 29.  28.4 37.8 30.2
 40.1 45.9 33.4 31.2 29.1 27.3 24.6 23.6 20.2 34.8 28.7  nan 24.1 17.4
 32.1 20.4 36.9 30.4 25.  31.6 57.9 24.3 18.4 20.7 18.2 35.4 30.5 34.4
 29.9 39.7 58.1 32.4 33.9 29.2 29.6 26.5 43.4 16.4 32.9 38.7 21.6 25.1
 27.9 34.1 23.4 20.5 35.6 33.3 28.1 24.  16.5 29.7 31.3 31.9 22.2 33.1
 24.5 30.6 32.5 29.8 36.8 19.2 27.1 31.5 48.4 32.7 22.  27.5 30.9 23.
 16.8 26.2 43.9 27.7 52.5 35.7 13.5 23.7 44.3 23.9 42.4 39.3 11.5 25.8
 15.  18.  28.  21.1 11.3 36.7 28.6 18.8 25.4 28.8 40.4 36.3 34.2 35.9
 19.5 26.6 20.9 45.1 41.3 35.8 49.5 13.4 23.5 41.5 43.3 21.5 53.5 45.5
 15.1 28.5 21.9 22.4 26.4 25.5 42.2 40.5 39.  29.3 14.3 31.  35.1 48.
 34.7 39.6 26.7 28.9 28.3 30.8 57.2 44.2 28.2 44.1 44.7 19.  36.6 19.7
 25.9 25.7 17.3 48.3 44.  18.5 53.4 16.7 46.6 16.1 22.7 18.7 14.4 34.
 19.3 48.9 19.4 21.8 31.8 32.  33.8 24.7 38.  19.1 37.3 52.3 18.1 19.8
 17.6 26.  33.7 48.1 34.3 17.9 35.  35.2 40.8 22.8 22.3 40.9 45.4 30.1
 37.9 22.1 17.1 43.6 40.  29.5 24.9 43.8 43.  33.5 34.6 32.6 43.7 20.
 37.1 39.5 25.3 55.  23.1 39.1 33.6 46.1 39.8 44.5 23.2 40.3 54.6 51.9
 15.5 56.1 26.9 14.6 23.8 41.1 17.  36.2 24.4 35.3 27.8 38.3 30.  37.2
 42.7 21.3 37.5 46.3 46.2 42.3 41.2 41.8 21.2 38.1 17.5 34.9 38.4 18.9
 16.  40.7 16.6 41.  48.2 21.  41.7 38.6 17.7 23.3 22.6 39.2 15.3 38.2
 45.  16.3 45.3 19.6 36.5 42.5 64.4 14.8 41.4 37.7 54.8 20.6 36.4 41.9
 49.4]
smoking_status
['never smoked' 'Unknown' 'formerly smoked' 'smokes']
stroke
[0 1]

# Clean Data

In [7]:
# check missing values
df.isna().sum()

id                    0
gender                0
age                   0
hypertension          0
heart_disease         0
ever_married          0
work_type             0
Residence_type        0
avg_glucose_level     0
bmi                  52
smoking_status        0
stroke                0
dtype: int64

In [8]:
# check duplicates
df.duplicated().sum()

np.int64(0)

# Preprocessing

In [9]:
# define x and y
x=df.drop(columns="stroke")
y=df["stroke"]

In [10]:
y.value_counts()

stroke
0    1000
1     137
Name: count, dtype: int64

In [11]:
# split data
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1)

In [12]:
# impute missing value with median
# build scaler
# build one hot encoder

num_cols = x_train.select_dtypes("number").columns
cat_cols = x_train.select_dtypes("object").columns
from sklearn.compose import ColumnTransformer
num_transformer = make_pipeline(SimpleImputer(strategy='median'), StandardScaler())
cat_transformer = make_pipeline(SimpleImputer(strategy='most_frequent'), OneHotEncoder(handle_unknown='ignore'))
preprocessor = ColumnTransformer([('num', num_transformer, num_cols), ('cat', cat_transformer, cat_cols)])

# Build Model

In [13]:
# build logistic regression moddel
lr=LogisticRegression(random_state=1)

In [14]:
# make pipeline
pipe=make_pipeline(preprocessor,lr)

In [15]:
# fir pipe on data
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  Index(['id', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi'], dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['gender', 'age', 'ever_married', 'work_type', 'Residence_type',
       'smoking_status'],
      dtype='object'))])),
                ('logisticregression', LogisticRegression(random_state=1))])

# Evaluate

In [16]:
# evaluate model using confusion matrix and report
# print accuracy of the model
y_pred=pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",pipe.score(x_train,y_train))
print("accuracy Testing:",pipe.score(x_test,y_test))

[[244   6]
 [ 32   3]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       250
           1       0.33      0.09      0.14        35

    accuracy                           0.87       285
   macro avg       0.61      0.53      0.53       285
weighted avg       0.82      0.87      0.83       285

accuracy Training: 0.8838028169014085
accuracy Testing: 0.8666666666666667

# Tuning to Get better results

In [17]:
# tunning the model using gridsearchcv
pipe.get_params()

{'memory': None,
 'steps': [('columntransformer',
   ColumnTransformer(transformers=[('num',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='median')),
                                                    ('standardscaler',
                                                     StandardScaler())]),
                                    Index(['id', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi'], dtype='object')),
                                   ('cat',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='most_frequent')),
                                                    ('onehotencoder',
                                                     OneHotEncoder(handle_unknown='ignore'))]),
                                    Index(['gender', 'age', 'ever_married', 'work_type', 'Residence_type',
          'smoking_status'],
         dtype='object'))])),
  ('logisticregression', LogisticRegression(random_state=1))],
 'transform_input': None,
 'verbose': False,
 'columntransformer': ColumnTransformer(transformers=[('num',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='median')),
                                                  ('standardscaler',
                                                   StandardScaler())]),
                                  Index(['id', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi'], dtype='object')),
                                 ('cat',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='most_frequent')),
                                                  ('onehotencoder',
                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                  Index(['gender', 'age', 'ever_married', 'work_type', 'Residence_type',
        'smoking_status'],
       dtype='object'))]),
 'logisticregression': LogisticRegression(random_state=1),
 'columntransformer__force_int_remainder_cols': True,
 'columntransformer__n_jobs': None,
 'columntransformer__remainder': 'drop',
 'columntransformer__sparse_threshold': 0.3,
 'columntransformer__transformer_weights': None,
 'columntransformer__transformers': [('num',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                   ('standardscaler', StandardScaler())]),
   Index(['id', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi'], dtype='object')),
  ('cat',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                   ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))]),
   Index(['gender', 'age', 'ever_married', 'work_type', 'Residence_type',
          'smoking_status'],
         dtype='object'))],
 'columntransformer__verbose': False,
 'columntransformer__verbose_feature_names_out': True,
 'columntransformer__num': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                 ('standardscaler', StandardScaler())]),
 'columntransformer__cat': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                 ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))]),
 'columntransformer__num__memory': None,
 'columntransformer__num__steps': [('simpleimputer',
   SimpleImputer(strategy='median')),
  ('standardscaler', StandardScaler())],
 'columntransformer__num__transform_input': None,
 'columntransformer__num__verbose': False,
 'columntransformer__num__simpleimputer': SimpleImputer(strategy='median'),
 'columntransformer__num__standardscaler': StandardScaler(),
 'columntransformer__num__simpleimputer__add_indicator': False,
 'columntransformer__num__simpleimputer__copy': True,
 'columntransformer__num__simpleimputer__fill_value': None,
 'columntransformer__num__simpleimputer__keep_empty_features': False,
 'columntransformer__num__simpleimputer__missing_values': nan,
 'columntransformer__num__simpleimputer__strategy': 'median',
 'columntransformer__num__standardscaler__copy': True,
 'columntransformer__num__standardscaler__with_mean': True,
 'columntransformer__num__standardscaler__with_std': True,
 'columntransformer__cat__memory': None,
 'columntransformer__cat__steps': [('simpleimputer',
   SimpleImputer(strategy='most_frequent')),
  ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))],
 'columntransformer__cat__transform_input': None,
 'columntransformer__cat__verbose': False,
 'columntransformer__cat__simpleimputer': SimpleImputer(strategy='most_frequent'),
 'columntransformer__cat__onehotencoder': OneHotEncoder(handle_unknown='ignore'),
 'columntransformer__cat__simpleimputer__add_indicator': False,
 'columntransformer__cat__simpleimputer__copy': True,
 'columntransformer__cat__simpleimputer__fill_value': None,
 'columntransformer__cat__simpleimputer__keep_empty_features': False,
 'columntransformer__cat__simpleimputer__missing_values': nan,
 'columntransformer__cat__simpleimputer__strategy': 'most_frequent',
 'columntransformer__cat__onehotencoder__categories': 'auto',
 'columntransformer__cat__onehotencoder__drop': None,
 'columntransformer__cat__onehotencoder__dtype': numpy.float64,
 'columntransformer__cat__onehotencoder__feature_name_combiner': 'concat',
 'columntransformer__cat__onehotencoder__handle_unknown': 'ignore',
 'columntransformer__cat__onehotencoder__max_categories': None,
 'columntransformer__cat__onehotencoder__min_frequency': None,
 'columntransformer__cat__onehotencoder__sparse_output': True,
 'logisticregression__C': 1.0,
 'logisticregression__class_weight': None,
 'logisticregression__dual': False,
 'logisticregression__fit_intercept': True,
 'logisticregression__intercept_scaling': 1,
 'logisticregression__l1_ratio': None,
 'logisticregression__max_iter': 100,
 'logisticregression__multi_class': 'deprecated',
 'logisticregression__n_jobs': None,
 'logisticregression__penalty': 'l2',
 'logisticregression__random_state': 1,
 'logisticregression__solver': 'lbfgs',
 'logisticregression__tol': 0.0001,
 'logisticregression__verbose': 0,
 'logisticregression__warm_start': False}

# Change Values of Parameters to get the best_params_

## C

In [18]:
# try diffrent values of 'logisticregression__C' to get the best_params_
param_grid={"logisticregression__C":[0.001,0.01,0.1, 1, 10, 100, 1000]}
grid=GridSearchCV(pipe,param_grid,cv=5)
grid.fit(x_train,y_train)
# get the best value
grid.best_params_

{'logisticregression__C': 0.001}

In [19]:
# rewrite the model with best value for c
lr=LogisticRegression(random_state=1,C=0.001)
pipe=make_pipeline(preprocessor,lr)
# evaluate the new version of model
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",pipe.score(x_train,y_train))
print("accuracy Testing:",pipe.score(x_test,y_test))

[[250   0]
 [ 35   0]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.93       250
           1       0.00      0.00      0.00        35

    accuracy                           0.88       285
   macro avg       0.44      0.50      0.47       285
weighted avg       0.77      0.88      0.82       285

accuracy Training: 0.8802816901408451
accuracy Testing: 0.8771929824561403

**The F1-Score increase alittle bit, but the results for class 1 are all zeros**

## solver

In [20]:
# # try diffrent values of 'logisticregression__solver' to get the best_params_
param_grid={"logisticregression__solver":["newton-cg", "lbfgs", "liblinear", "sag", "saga"]}
grid=GridSearchCV(pipe,param_grid,cv=5)
grid.fit(x_train,y_train)
# get the best value
grid.best_params_

{'logisticregression__solver': 'newton-cg'}

In [21]:

# build the new version with newton-cg
lr=LogisticRegression(random_state=1,solver="newton-cg")
# evaluate the model
pipe=make_pipeline(preprocessor,lr)
# evaluate the new version of model
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",pipe.score(x_train,y_train))
print("accuracy Testing:",pipe.score(x_test,y_test))

[[244   6]
 [ 32   3]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       250
           1       0.33      0.09      0.14        35

    accuracy                           0.87       285
   macro avg       0.61      0.53      0.53       285
weighted avg       0.82      0.87      0.83       285

accuracy Training: 0.8838028169014085
accuracy Testing: 0.8666666666666667

**The reults is the same for the defult parameters**

##penalty

In [22]:
# try diffrent values of logisticregression__penalty and 'logisticregression__solver' to get the best_params_
param_grid = {
    'logisticregression__penalty': ['l1', 'l2'],
    'logisticregression__solver': ['liblinear', 'saga']
}
grid = GridSearchCV(pipe, param_grid)
grid.fit(x_train, y_train)
print(grid.best_params_)

{'logisticregression__penalty': 'l2', 'logisticregression__solver': 'saga'}

In [23]:
# try the new values of parameters
lr = LogisticRegression(random_state=1, penalty='l1', solver='liblinear')
pipe = make_pipeline(preprocessor, lr)
pipe.fit(x_train, y_train)
y_pred = pipe.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[243   7]
 [ 32   3]]
              precision    recall  f1-score   support

           0       0.88      0.97      0.93       250
           1       0.30      0.09      0.13        35

    accuracy                           0.86       285
   macro avg       0.59      0.53      0.53       285
weighted avg       0.81      0.86      0.83       285

**the F1-Score Decrease**

In [24]:
# try the another values of parameters
lr = LogisticRegression(random_state=1, penalty='l2')
pipe = make_pipeline(preprocessor, lr)
pipe.fit(x_train, y_train)
y_pred = pipe.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[244   6]
 [ 32   3]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       250
           1       0.33      0.09      0.14        35

    accuracy                           0.87       285
   macro avg       0.61      0.53      0.53       285
weighted avg       0.82      0.87      0.83       285

## max_iter

In [25]:
# Change the max_iter
param_grid = {'logisticregression__max_iter': [10,20,50,100,200,300,400,500]}
grid = GridSearchCV(pipe, param_grid)
grid.fit(x_train, y_train)
print(grid.best_params_)

{'logisticregression__max_iter': 10}

In [26]:
# try the new value of parameters
lr = LogisticRegression(random_state=1, max_iter=10)
pipe = make_pipeline(preprocessor, lr)
pipe.fit(x_train, y_train)
y_pred = pipe.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[244   6]
 [ 32   3]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       250
           1       0.33      0.09      0.14        35

    accuracy                           0.87       285
   macro avg       0.61      0.53      0.53       285
weighted avg       0.82      0.87      0.83       285

**The results didn't change, logisticregression__max_iter is Not The Most effect Parameter**

## class_weight

In [27]:
 # try diffrent values of logisticregression__class_weight to get the best_params_
param_grid = {'logisticregression__class_weight': ['balanced', None]}
grid = GridSearchCV(pipe, param_grid)
grid.fit(x_train, y_train)
print(grid.best_params_)

{'logisticregression__class_weight': None}

In [28]:
# try the new value of parameters
lr = LogisticRegression(random_state=1,class_weight='balanced')
pipe = make_pipeline(preprocessor, lr)
pipe.fit(x_train, y_train)
y_pred = pipe.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[193  57]
 [ 14  21]]
              precision    recall  f1-score   support

           0       0.93      0.77      0.84       250
           1       0.27      0.60      0.37        35

    accuracy                           0.75       285
   macro avg       0.60      0.69      0.61       285
weighted avg       0.85      0.75      0.79       285

**The weighted avg increases, However the F1-Score decreaes**

## l1_ratio

In [29]:
 # try diffrent values of logisticregression__l1_ratio to get the best_params_
param_grid = {'logisticregression__l1_ratio': [0.0, 0.25, 0.5, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]}
grid = GridSearchCV(pipe, param_grid)
grid.fit(x_train, y_train)
print(grid.best_params_)

{'logisticregression__l1_ratio': 0.0}

In [30]:
# try the new value
lr = LogisticRegression(random_state=1,l1_ratio=0.0)
pipe = make_pipeline(preprocessor, lr)
pipe.fit(x_train, y_train)
y_pred = pipe.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[244   6]
 [ 32   3]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       250
           1       0.33      0.09      0.14        35

    accuracy                           0.87       285
   macro avg       0.61      0.53      0.53       285
weighted avg       0.82      0.87      0.83       285

**it Didn't Change**

# Result

**For this Data Set - > The moset effective parameter is c , then pantly and class_weight**

In [31]:
# Build The model
lr=LogisticRegression(random_state=1, penalty='l2',solver="newton-cg",C=0.001)
pipe=make_pipeline(preprocessor,lr)
# evaluate the new version of model
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",pipe.score(x_train,y_train))
print("accuracy Testing:",pipe.score(x_test,y_test))

[[250   0]
 [ 35   0]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.93       250
           1       0.00      0.00      0.00        35

    accuracy                           0.88       285
   macro avg       0.44      0.50      0.47       285
weighted avg       0.77      0.88      0.82       285

accuracy Training: 0.8802816901408451
accuracy Testing: 0.8771929824561403

In [32]:
param_grid = {'logisticregression__l1_ratio': [0.0, 0.25, 0.5, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1],
              'logisticregression__class_weight': ['balanced', None],
              'logisticregression__max_iter': [10,20,50,100,200,300,400,500],
               'logisticregression__penalty': ['l1', 'l2'],
               'logisticregression__solver': ['liblinear', 'saga'],
              "logisticregression__C":[0.001,0.01,0.1, 1, 10, 100, 1000]
}
grid = GridSearchCV(pipe, param_grid)
grid.fit(x_train, y_train)
print(grid.best_params_)

{'logisticregression__C': 0.01, 'logisticregression__class_weight': None, 'logisticregression__l1_ratio': 0.0, 'logisticregression__max_iter': 10, 'logisticregression__penalty': 'l2', 'logisticregression__solver': 'liblinear'}

In [33]:
# Build The model
lr=LogisticRegression(random_state=1, penalty='l2',solver="liblinear",C=0.01)
pipe=make_pipeline(preprocessor,lr)
# evaluate the new version of model
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",pipe.score(x_train,y_train))
print("accuracy Testing:",pipe.score(x_test,y_test))

[[250   0]
 [ 35   0]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.93       250
           1       0.00      0.00      0.00        35

    accuracy                           0.88       285
   macro avg       0.44      0.50      0.47       285
weighted avg       0.77      0.88      0.82       285

accuracy Training: 0.8826291079812206
accuracy Testing: 0.8771929824561403

# Balancing

## Under sampling

In [34]:
# Under sampling to make the data balance
from imblearn.under_sampling import RandomUnderSampler
rus=RandomUnderSampler(random_state=1)
under_sample_pipe=make_pipeline(preprocessor,rus)
x_train_rus,y_train_rus=rus.fit_resample(x_train,y_train)
y_train_rus.value_counts()

stroke
0    102
1    102
Name: count, dtype: int64

In [66]:
# Build The model after undersampling with best parameter
#import imblearn pipeline
from imblearn.pipeline import make_pipeline as make_pipeline_imb
lr=LogisticRegression(random_state=1, penalty='l2',solver="newton-cg",C=0.01)
under_sample_pipe=make_pipeline_imb(preprocessor,rus,lr)
under_sample_pipe.fit(x_train_rus,y_train_rus)
y_pred=under_sample_pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",under_sample_pipe.score(x_train_rus,y_train_rus))
print("accuracy Testing:",under_sample_pipe.score(x_test,y_test))

[[187  63]
 [ 18  17]]
              precision    recall  f1-score   support

           0       0.91      0.75      0.82       250
           1       0.21      0.49      0.30        35

    accuracy                           0.72       285
   macro avg       0.56      0.62      0.56       285
weighted avg       0.83      0.72      0.76       285

accuracy Training: 0.6666666666666666
accuracy Testing: 0.7157894736842105

In [67]:
# Build The model
lr=LogisticRegression(random_state=1)
under_sample_pipe=make_pipeline_imb(preprocessor,rus,lr)
under_sample_pipe.fit(x_train_rus,y_train_rus)
y_pred=under_sample_pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",under_sample_pipe.score(x_train_rus,y_train_rus))
print("accuracy Testing:",under_sample_pipe.score(x_test,y_test))

[[169  81]
 [ 15  20]]
              precision    recall  f1-score   support

           0       0.92      0.68      0.78       250
           1       0.20      0.57      0.29        35

    accuracy                           0.66       285
   macro avg       0.56      0.62      0.54       285
weighted avg       0.83      0.66      0.72       285

accuracy Training: 0.7990196078431373
accuracy Testing: 0.6631578947368421

## Oversampling

In [48]:
# oversampling to acheive balance
from imblearn.over_sampling import RandomOverSampler
ros=RandomOverSampler(random_state=1)
over_sample_pipe=make_pipeline(preprocessor,ros,lr)
x_train_ros,y_train_ros=ros.fit_resample(x_train,y_train)
y_train_ros.value_counts()

stroke
0    750
1    750
Name: count, dtype: int64

In [62]:
# Build The model after oversampling with best parameter
lr=LogisticRegression(random_state=1, penalty='l2',solver="newton-cg",C=0.01)
over_sample_pipe=make_pipeline(preprocessor,ros,lr)
over_sample_pipe.fit(x_train_ros,y_train_ros)
y_pred=over_sample_pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",over_sample_pipe.score(x_train_ros,y_train_ros))
print("accuracy Testing:",over_sample_pipe.score(x_test,y_test))

[[190  60]
 [ 16  19]]
              precision    recall  f1-score   support

           0       0.92      0.76      0.83       250
           1       0.24      0.54      0.33        35

    accuracy                           0.73       285
   macro avg       0.58      0.65      0.58       285
weighted avg       0.84      0.73      0.77       285

accuracy Training: 0.724
accuracy Testing: 0.7333333333333333

In [63]:
lr=LogisticRegression(random_state=1)
over_sample_pipe=make_pipeline(preprocessor,ros,lr)
over_sample_pipe.fit(x_train_ros,y_train_ros)
y_pred=over_sample_pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",over_sample_pipe.score(x_train_ros,y_train_ros))
print("accuracy Testing:",over_sample_pipe.score(x_test,y_test))

[[195  55]
 [ 14  21]]
              precision    recall  f1-score   support

           0       0.93      0.78      0.85       250
           1       0.28      0.60      0.38        35

    accuracy                           0.76       285
   macro avg       0.60      0.69      0.61       285
weighted avg       0.85      0.76      0.79       285

accuracy Training: 0.8186666666666667
accuracy Testing: 0.7578947368421053

## Smote

In [68]:
#Create model pipeline with scaler, SMOTE, and model
from imblearn.over_sampling import SMOTE
smote = SMOTE()
log_reg_smote = LogisticRegression(random_state=1)
log_reg_smote_pipe = make_pipeline(preprocessor, smote, log_reg_smote)
#Fit and evaluate the model pipeline
log_reg_smote_pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  Index(['id', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi'], dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['gender', 'age', 'ever_married', 'work_type', 'Residence_type',
       'smoking_status'],
      dtype='object'))])),
                ('smote', SMOTE()),
                ('logisticregression', LogisticRegression(random_state=1))])

In [69]:
# predict uing smote
y_pred=log_reg_smote_pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",log_reg_smote_pipe.score(x_train,y_train))
print("accuracy Testing:",log_reg_smote_pipe.score(x_test,y_test))

[[199  51]
 [ 15  20]]
              precision    recall  f1-score   support

           0       0.93      0.80      0.86       250
           1       0.28      0.57      0.38        35

    accuracy                           0.77       285
   macro avg       0.61      0.68      0.62       285
weighted avg       0.85      0.77      0.80       285

accuracy Training: 0.7852112676056338
accuracy Testing: 0.7684210526315789

In [74]:
log_reg_smote = LogisticRegression(penalty='l2',solver="newton-cg",C=0.01,random_state=1)

log_reg_smote_pipe = make_pipeline(preprocessor, smote, log_reg_smote)
#Fit and evaluate the model pipeline
log_reg_smote_pipe.fit(x_train, y_train)
y_pred=log_reg_smote_pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",log_reg_smote_pipe.score(x_train,y_train))
print("accuracy Testing:",log_reg_smote_pipe.score(x_test,y_test))

[[192  58]
 [ 16  19]]
              precision    recall  f1-score   support

           0       0.92      0.77      0.84       250
           1       0.25      0.54      0.34        35

    accuracy                           0.74       285
   macro avg       0.58      0.66      0.59       285
weighted avg       0.84      0.74      0.78       285

accuracy Training: 0.7511737089201878
accuracy Testing: 0.7403508771929824

**The Best logistic Regression Model was defult parameters with Smote with the less overfitting and balanced classes and the F1-score was 77**

# feature importances

In [44]:
# Obtain feature importances from the fit model
lr. feature_importances_

AttributeError: 'LogisticRegression' object has no attribute 'feature_importances_'

In [ ]:
# Saving the feature importances
feature_names=lr. feature_importances_
importances = pd. Series(lr. feature_importances_, index= feature_names,
name='Feature Importance' )

importances

In [ ]:
# Saving the feature importances sorted from smallest to largest (ascending=True)
sorted_importance = importances.sort_values()
sorted_importance

In [ ]:
# Using plt.gcf to get the fig
ax = sorted_importance.tail(10).plot(kind='barh',
figsize=(8,6), xlabel='Importance',
ylabel='Feature Name',
title='Top 10 Most Important Features')

fig_gcf = plt.gcf()

In [ ]:
def get_importances(model, feature_names=None, name='Feature Importance',
sort=False, ascending=True) :

## checking for feature names
  if feature_names == None:
      feature_names = model. feature_names_in_

## Saving the feature importances
  importances = pd. Series(model. feature_importances_, index= feature_names,name=name)

# sort importances
  if sort == True:
    importances = importances. sort_values(ascending=ascending)

   return importances

# CatBoost

In [46]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.2 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [126]:
# import Catbosstclassifier
from catboost import CatBoostClassifier
# build catboostmodel

cbc=CatBoostClassifier(random_state=1)
pipe=make_pipeline(preprocessor,cbc)
pipe.fit(x_train,y_train)
#evaluate
y_pred=pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",pipe.score(x_train,y_train))
print("accuracy Testing:",pipe.score(x_test,y_test))

Learning rate set to 0.009621
0:	learn: 0.6839715	total: 3.81ms	remaining: 3.81s
1:	learn: 0.6753530	total: 5.67ms	remaining: 2.83s
2:	learn: 0.6677480	total: 7.34ms	remaining: 2.44s
3:	learn: 0.6590313	total: 9.09ms	remaining: 2.26s
4:	learn: 0.6514893	total: 10.9ms	remaining: 2.17s
5:	learn: 0.6437210	total: 12.7ms	remaining: 2.1s
6:	learn: 0.6361502	total: 14.5ms	remaining: 2.06s
7:	learn: 0.6292995	total: 16.3ms	remaining: 2.02s
8:	learn: 0.6231752	total: 18.1ms	remaining: 1.99s
9:	learn: 0.6157800	total: 19.9ms	remaining: 1.97s
10:	learn: 0.6090417	total: 21.6ms	remaining: 1.95s
11:	learn: 0.6027175	total: 23.4ms	remaining: 1.93s
12:	learn: 0.5967388	total: 25.1ms	remaining: 1.91s
13:	learn: 0.5907185	total: 26.9ms	remaining: 1.9s
14:	learn: 0.5839684	total: 28.7ms	remaining: 1.88s
15:	learn: 0.5782013	total: 30.5ms	remaining: 1.88s
16:	learn: 0.5728200	total: 32.3ms	remaining: 1.87s
17:	learn: 0.5674006	total: 34.1ms	remaining: 1.86s
18:	learn: 0.5623280	total: 35.8ms	remaining: 1.85s
19:	learn: 0.5573338	total: 37.6ms	remaining: 1.84s
20:	learn: 0.5511553	total: 39.4ms	remaining: 1.83s
21:	learn: 0.5460002	total: 41ms	remaining: 1.82s
22:	learn: 0.5416729	total: 42.8ms	remaining: 1.82s
23:	learn: 0.5368614	total: 44.6ms	remaining: 1.81s
24:	learn: 0.5312435	total: 46.3ms	remaining: 1.81s
25:	learn: 0.5271359	total: 48.2ms	remaining: 1.8s
26:	learn: 0.5232682	total: 49.6ms	remaining: 1.79s
27:	learn: 0.5183957	total: 51.4ms	remaining: 1.78s
28:	learn: 0.5139865	total: 53ms	remaining: 1.77s
29:	learn: 0.5090028	total: 54.6ms	remaining: 1.77s
30:	learn: 0.5052347	total: 56.4ms	remaining: 1.76s
31:	learn: 0.5018738	total: 58.3ms	remaining: 1.76s
32:	learn: 0.4974237	total: 60.1ms	remaining: 1.76s
33:	learn: 0.4938591	total: 61.9ms	remaining: 1.76s
34:	learn: 0.4903830	total: 63.7ms	remaining: 1.75s
35:	learn: 0.4864819	total: 65.5ms	remaining: 1.75s
36:	learn: 0.4829142	total: 67.3ms	remaining: 1.75s
37:	learn: 0.4787427	total: 69ms	remaining: 1.75s
38:	learn: 0.4748423	total: 70.3ms	remaining: 1.73s
39:	learn: 0.4714338	total: 72ms	remaining: 1.73s
40:	learn: 0.4685873	total: 74ms	remaining: 1.73s
41:	learn: 0.4651071	total: 75.8ms	remaining: 1.73s
42:	learn: 0.4616365	total: 77.6ms	remaining: 1.73s
43:	learn: 0.4578115	total: 79.4ms	remaining: 1.72s
44:	learn: 0.4553703	total: 81.1ms	remaining: 1.72s
45:	learn: 0.4529506	total: 82.2ms	remaining: 1.7s
46:	learn: 0.4494619	total: 84ms	remaining: 1.7s
47:	learn: 0.4467237	total: 85.8ms	remaining: 1.7s
48:	learn: 0.4442279	total: 87.6ms	remaining: 1.7s
49:	learn: 0.4411337	total: 89.2ms	remaining: 1.7s
50:	learn: 0.4387609	total: 90.8ms	remaining: 1.69s
51:	learn: 0.4365308	total: 92.1ms	remaining: 1.68s
52:	learn: 0.4337407	total: 93.9ms	remaining: 1.68s
53:	learn: 0.4308406	total: 95.8ms	remaining: 1.68s
54:	learn: 0.4282606	total: 97.1ms	remaining: 1.67s
55:	learn: 0.4257244	total: 98.9ms	remaining: 1.67s
56:	learn: 0.4228500	total: 101ms	remaining: 1.67s
57:	learn: 0.4206661	total: 102ms	remaining: 1.66s
58:	learn: 0.4185079	total: 104ms	remaining: 1.66s
59:	learn: 0.4161676	total: 106ms	remaining: 1.66s
60:	learn: 0.4143925	total: 108ms	remaining: 1.66s
61:	learn: 0.4118602	total: 109ms	remaining: 1.65s
62:	learn: 0.4095657	total: 111ms	remaining: 1.65s
63:	learn: 0.4072996	total: 113ms	remaining: 1.65s
64:	learn: 0.4048737	total: 115ms	remaining: 1.65s
65:	learn: 0.4028617	total: 117ms	remaining: 1.65s
66:	learn: 0.4008418	total: 118ms	remaining: 1.65s
67:	learn: 0.3982724	total: 120ms	remaining: 1.65s
68:	learn: 0.3962924	total: 122ms	remaining: 1.64s
69:	learn: 0.3941490	total: 124ms	remaining: 1.64s
70:	learn: 0.3923600	total: 125ms	remaining: 1.64s
71:	learn: 0.3911297	total: 126ms	remaining: 1.63s
72:	learn: 0.3888143	total: 128ms	remaining: 1.62s
73:	learn: 0.3869017	total: 130ms	remaining: 1.62s
74:	learn: 0.3851338	total: 131ms	remaining: 1.62s
75:	learn: 0.3838341	total: 132ms	remaining: 1.61s
76:	learn: 0.3826132	total: 134ms	remaining: 1.6s
77:	learn: 0.3815169	total: 135ms	remaining: 1.6s
78:	learn: 0.3801594	total: 137ms	remaining: 1.6s
79:	learn: 0.3786333	total: 139ms	remaining: 1.6s
80:	learn: 0.3768266	total: 141ms	remaining: 1.6s
81:	learn: 0.3751080	total: 143ms	remaining: 1.6s
82:	learn: 0.3740680	total: 145ms	remaining: 1.6s
83:	learn: 0.3723862	total: 146ms	remaining: 1.6s
84:	learn: 0.3713084	total: 148ms	remaining: 1.59s
85:	learn: 0.3696982	total: 150ms	remaining: 1.59s
86:	learn: 0.3686377	total: 152ms	remaining: 1.59s
87:	learn: 0.3673269	total: 154ms	remaining: 1.59s
88:	learn: 0.3657416	total: 155ms	remaining: 1.59s
89:	learn: 0.3646586	total: 157ms	remaining: 1.59s
90:	learn: 0.3632591	total: 159ms	remaining: 1.58s
91:	learn: 0.3620137	total: 160ms	remaining: 1.58s
92:	learn: 0.3604655	total: 162ms	remaining: 1.58s
93:	learn: 0.3589152	total: 163ms	remaining: 1.57s
94:	learn: 0.3574460	total: 165ms	remaining: 1.57s
95:	learn: 0.3562189	total: 167ms	remaining: 1.57s
96:	learn: 0.3545443	total: 169ms	remaining: 1.57s
97:	learn: 0.3531776	total: 170ms	remaining: 1.57s
98:	learn: 0.3516606	total: 172ms	remaining: 1.57s
99:	learn: 0.3502319	total: 174ms	remaining: 1.56s
100:	learn: 0.3490502	total: 176ms	remaining: 1.56s
101:	learn: 0.3479188	total: 178ms	remaining: 1.56s
102:	learn: 0.3469220	total: 180ms	remaining: 1.56s
103:	learn: 0.3456582	total: 182ms	remaining: 1.56s
104:	learn: 0.3447613	total: 183ms	remaining: 1.56s
105:	learn: 0.3437528	total: 185ms	remaining: 1.56s
106:	learn: 0.3425475	total: 188ms	remaining: 1.57s
107:	learn: 0.3414677	total: 191ms	remaining: 1.58s
108:	learn: 0.3402928	total: 194ms	remaining: 1.59s
109:	learn: 0.3391236	total: 196ms	remaining: 1.59s
110:	learn: 0.3382062	total: 199ms	remaining: 1.59s
111:	learn: 0.3372859	total: 201ms	remaining: 1.59s
112:	learn: 0.3368536	total: 201ms	remaining: 1.58s
113:	learn: 0.3359268	total: 204ms	remaining: 1.58s
114:	learn: 0.3346762	total: 206ms	remaining: 1.58s
115:	learn: 0.3339470	total: 207ms	remaining: 1.58s
116:	learn: 0.3330392	total: 209ms	remaining: 1.58s
117:	learn: 0.3322937	total: 211ms	remaining: 1.58s
118:	learn: 0.3313663	total: 213ms	remaining: 1.57s
119:	learn: 0.3305853	total: 214ms	remaining: 1.57s
120:	learn: 0.3299709	total: 216ms	remaining: 1.57s
121:	learn: 0.3291784	total: 218ms	remaining: 1.57s
122:	learn: 0.3285440	total: 220ms	remaining: 1.57s
123:	learn: 0.3280383	total: 222ms	remaining: 1.56s
124:	learn: 0.3271050	total: 223ms	remaining: 1.56s
125:	learn: 0.3260471	total: 225ms	remaining: 1.56s
126:	learn: 0.3253050	total: 228ms	remaining: 1.57s
127:	learn: 0.3244280	total: 232ms	remaining: 1.58s
128:	learn: 0.3238110	total: 236ms	remaining: 1.59s
129:	learn: 0.3230650	total: 240ms	remaining: 1.61s
130:	learn: 0.3225394	total: 249ms	remaining: 1.65s
131:	learn: 0.3219164	total: 254ms	remaining: 1.67s
132:	learn: 0.3212834	total: 259ms	remaining: 1.69s
133:	learn: 0.3205896	total: 265ms	remaining: 1.71s
134:	learn: 0.3194829	total: 271ms	remaining: 1.74s
135:	learn: 0.3185062	total: 277ms	remaining: 1.76s
136:	learn: 0.3176638	total: 283ms	remaining: 1.78s
137:	learn: 0.3172758	total: 288ms	remaining: 1.8s
138:	learn: 0.3165631	total: 294ms	remaining: 1.82s
139:	learn: 0.3160844	total: 300ms	remaining: 1.84s
140:	learn: 0.3154758	total: 305ms	remaining: 1.86s
141:	learn: 0.3150606	total: 309ms	remaining: 1.87s
142:	learn: 0.3144662	total: 316ms	remaining: 1.89s
143:	learn: 0.3134794	total: 321ms	remaining: 1.91s
144:	learn: 0.3125633	total: 328ms	remaining: 1.93s
145:	learn: 0.3116205	total: 333ms	remaining: 1.95s
146:	learn: 0.3110994	total: 339ms	remaining: 1.97s
147:	learn: 0.3103345	total: 345ms	remaining: 1.99s
148:	learn: 0.3097592	total: 351ms	remaining: 2.01s
149:	learn: 0.3092059	total: 356ms	remaining: 2.02s
150:	learn: 0.3084157	total: 363ms	remaining: 2.04s
151:	learn: 0.3079071	total: 368ms	remaining: 2.05s
152:	learn: 0.3073341	total: 375ms	remaining: 2.07s
153:	learn: 0.3065016	total: 380ms	remaining: 2.08s
154:	learn: 0.3060425	total: 386ms	remaining: 2.1s
155:	learn: 0.3053574	total: 393ms	remaining: 2.13s
156:	learn: 0.3049138	total: 400ms	remaining: 2.15s
157:	learn: 0.3045325	total: 404ms	remaining: 2.15s
158:	learn: 0.3039829	total: 411ms	remaining: 2.17s
159:	learn: 0.3032891	total: 415ms	remaining: 2.18s
160:	learn: 0.3026366	total: 422ms	remaining: 2.2s
161:	learn: 0.3019245	total: 427ms	remaining: 2.21s
162:	learn: 0.3015242	total: 433ms	remaining: 2.22s
163:	learn: 0.3009019	total: 439ms	remaining: 2.24s
164:	learn: 0.3002711	total: 445ms	remaining: 2.25s
165:	learn: 0.2996240	total: 448ms	remaining: 2.25s
166:	learn: 0.2992861	total: 450ms	remaining: 2.24s
167:	learn: 0.2987562	total: 457ms	remaining: 2.26s
168:	learn: 0.2980488	total: 461ms	remaining: 2.27s
169:	learn: 0.2973248	total: 466ms	remaining: 2.28s
170:	learn: 0.2970109	total: 472ms	remaining: 2.29s
171:	learn: 0.2964431	total: 476ms	remaining: 2.29s
172:	learn: 0.2960752	total: 480ms	remaining: 2.29s
173:	learn: 0.2953447	total: 485ms	remaining: 2.3s
174:	learn: 0.2948417	total: 489ms	remaining: 2.31s
175:	learn: 0.2941219	total: 494ms	remaining: 2.31s
176:	learn: 0.2936270	total: 500ms	remaining: 2.32s
177:	learn: 0.2932550	total: 505ms	remaining: 2.33s
178:	learn: 0.2927749	total: 509ms	remaining: 2.33s
179:	learn: 0.2923499	total: 514ms	remaining: 2.34s
180:	learn: 0.2918797	total: 520ms	remaining: 2.35s
181:	learn: 0.2913912	total: 526ms	remaining: 2.36s
182:	learn: 0.2908982	total: 531ms	remaining: 2.37s
183:	learn: 0.2904019	total: 537ms	remaining: 2.38s
184:	learn: 0.2898544	total: 543ms	remaining: 2.39s
185:	learn: 0.2894219	total: 548ms	remaining: 2.4s
186:	learn: 0.2891643	total: 554ms	remaining: 2.41s
187:	learn: 0.2884801	total: 559ms	remaining: 2.41s
188:	learn: 0.2880546	total: 562ms	remaining: 2.41s
189:	learn: 0.2875739	total: 565ms	remaining: 2.41s
190:	learn: 0.2872617	total: 572ms	remaining: 2.42s
191:	learn: 0.2869311	total: 577ms	remaining: 2.43s
192:	learn: 0.2865590	total: 583ms	remaining: 2.44s
193:	learn: 0.2861968	total: 589ms	remaining: 2.45s
194:	learn: 0.2859021	total: 597ms	remaining: 2.46s
195:	learn: 0.2855351	total: 602ms	remaining: 2.47s
196:	learn: 0.2851086	total: 608ms	remaining: 2.48s
197:	learn: 0.2847252	total: 613ms	remaining: 2.48s
198:	learn: 0.2841913	total: 620ms	remaining: 2.5s
199:	learn: 0.2838393	total: 624ms	remaining: 2.5s
200:	learn: 0.2832732	total: 631ms	remaining: 2.51s
201:	learn: 0.2827769	total: 636ms	remaining: 2.51s
202:	learn: 0.2824884	total: 640ms	remaining: 2.51s
203:	learn: 0.2821650	total: 647ms	remaining: 2.52s
204:	learn: 0.2817205	total: 652ms	remaining: 2.53s
205:	learn: 0.2812491	total: 656ms	remaining: 2.53s
206:	learn: 0.2808349	total: 663ms	remaining: 2.54s
207:	learn: 0.2804638	total: 667ms	remaining: 2.54s
208:	learn: 0.2801454	total: 671ms	remaining: 2.54s
209:	learn: 0.2796707	total: 678ms	remaining: 2.55s
210:	learn: 0.2791118	total: 683ms	remaining: 2.55s
211:	learn: 0.2788249	total: 687ms	remaining: 2.55s
212:	learn: 0.2785320	total: 691ms	remaining: 2.55s
213:	learn: 0.2780742	total: 697ms	remaining: 2.56s
214:	learn: 0.2777570	total: 702ms	remaining: 2.56s
215:	learn: 0.2774541	total: 707ms	remaining: 2.56s
216:	learn: 0.2770627	total: 710ms	remaining: 2.56s
217:	learn: 0.2767987	total: 716ms	remaining: 2.57s
218:	learn: 0.2765024	total: 720ms	remaining: 2.57s
219:	learn: 0.2761491	total: 725ms	remaining: 2.57s
220:	learn: 0.2756467	total: 730ms	remaining: 2.57s
221:	learn: 0.2753938	total: 734ms	remaining: 2.57s
222:	learn: 0.2749879	total: 739ms	remaining: 2.57s
223:	learn: 0.2745333	total: 746ms	remaining: 2.58s
224:	learn: 0.2742006	total: 750ms	remaining: 2.58s
225:	learn: 0.2740156	total: 754ms	remaining: 2.58s
226:	learn: 0.2736169	total: 761ms	remaining: 2.59s
227:	learn: 0.2733769	total: 766ms	remaining: 2.59s
228:	learn: 0.2732988	total: 769ms	remaining: 2.59s
229:	learn: 0.2727166	total: 774ms	remaining: 2.59s
230:	learn: 0.2724809	total: 778ms	remaining: 2.59s
231:	learn: 0.2720631	total: 787ms	remaining: 2.6s
232:	learn: 0.2717943	total: 793ms	remaining: 2.61s
233:	learn: 0.2714626	total: 800ms	remaining: 2.62s
234:	learn: 0.2712347	total: 805ms	remaining: 2.62s
235:	learn: 0.2708148	total: 811ms	remaining: 2.63s
236:	learn: 0.2704032	total: 816ms	remaining: 2.63s
237:	learn: 0.2700267	total: 823ms	remaining: 2.63s
238:	learn: 0.2699672	total: 827ms	remaining: 2.63s
239:	learn: 0.2697765	total: 833ms	remaining: 2.64s
240:	learn: 0.2694899	total: 838ms	remaining: 2.64s
241:	learn: 0.2692484	total: 842ms	remaining: 2.64s
242:	learn: 0.2688805	total: 847ms	remaining: 2.64s
243:	learn: 0.2686247	total: 853ms	remaining: 2.64s
244:	learn: 0.2682550	total: 861ms	remaining: 2.65s
245:	learn: 0.2678464	total: 867ms	remaining: 2.66s
246:	learn: 0.2675169	total: 874ms	remaining: 2.66s
247:	learn: 0.2671220	total: 879ms	remaining: 2.67s
248:	learn: 0.2669689	total: 885ms	remaining: 2.67s
249:	learn: 0.2666383	total: 891ms	remaining: 2.67s
250:	learn: 0.2663334	total: 899ms	remaining: 2.68s
251:	learn: 0.2661783	total: 907ms	remaining: 2.69s
252:	learn: 0.2657782	total: 914ms	remaining: 2.7s
253:	learn: 0.2654941	total: 920ms	remaining: 2.7s
254:	learn: 0.2651373	total: 925ms	remaining: 2.7s
255:	learn: 0.2648587	total: 929ms	remaining: 2.7s
256:	learn: 0.2644136	total: 936ms	remaining: 2.71s
257:	learn: 0.2640836	total: 942ms	remaining: 2.71s
258:	learn: 0.2637214	total: 949ms	remaining: 2.71s
259:	learn: 0.2633280	total: 954ms	remaining: 2.71s
260:	learn: 0.2631363	total: 958ms	remaining: 2.71s
261:	learn: 0.2629001	total: 963ms	remaining: 2.71s
262:	learn: 0.2626134	total: 968ms	remaining: 2.71s
263:	learn: 0.2623411	total: 975ms	remaining: 2.72s
264:	learn: 0.2620175	total: 980ms	remaining: 2.72s
265:	learn: 0.2617033	total: 986ms	remaining: 2.72s
266:	learn: 0.2613554	total: 993ms	remaining: 2.73s
267:	learn: 0.2610944	total: 999ms	remaining: 2.73s
268:	learn: 0.2608228	total: 1s	remaining: 2.73s
269:	learn: 0.2601802	total: 1.01s	remaining: 2.73s
270:	learn: 0.2598313	total: 1.02s	remaining: 2.74s
271:	learn: 0.2596018	total: 1.02s	remaining: 2.74s
272:	learn: 0.2592624	total: 1.03s	remaining: 2.74s
273:	learn: 0.2590031	total: 1.04s	remaining: 2.75s
274:	learn: 0.2588424	total: 1.04s	remaining: 2.75s
275:	learn: 0.2586207	total: 1.05s	remaining: 2.75s
276:	learn: 0.2584863	total: 1.05s	remaining: 2.74s
277:	learn: 0.2583259	total: 1.06s	remaining: 2.75s
278:	learn: 0.2580084	total: 1.06s	remaining: 2.75s
279:	learn: 0.2577467	total: 1.07s	remaining: 2.75s
280:	learn: 0.2575231	total: 1.07s	remaining: 2.75s
281:	learn: 0.2572324	total: 1.08s	remaining: 2.75s
282:	learn: 0.2569384	total: 1.08s	remaining: 2.75s
283:	learn: 0.2566740	total: 1.09s	remaining: 2.75s
284:	learn: 0.2565073	total: 1.1s	remaining: 2.75s
285:	learn: 0.2562151	total: 1.1s	remaining: 2.75s
286:	learn: 0.2559502	total: 1.11s	remaining: 2.75s
287:	learn: 0.2555655	total: 1.11s	remaining: 2.75s
288:	learn: 0.2552984	total: 1.12s	remaining: 2.76s
289:	learn: 0.2550955	total: 1.13s	remaining: 2.75s
290:	learn: 0.2548162	total: 1.13s	remaining: 2.76s
291:	learn: 0.2546425	total: 1.14s	remaining: 2.76s
292:	learn: 0.2544348	total: 1.14s	remaining: 2.76s
293:	learn: 0.2540370	total: 1.15s	remaining: 2.76s
294:	learn: 0.2536096	total: 1.15s	remaining: 2.76s
295:	learn: 0.2531672	total: 1.16s	remaining: 2.76s
296:	learn: 0.2529477	total: 1.17s	remaining: 2.76s
297:	learn: 0.2526696	total: 1.17s	remaining: 2.76s
298:	learn: 0.2522804	total: 1.18s	remaining: 2.76s
299:	learn: 0.2519843	total: 1.18s	remaining: 2.76s
300:	learn: 0.2517692	total: 1.19s	remaining: 2.77s
301:	learn: 0.2515192	total: 1.2s	remaining: 2.77s
302:	learn: 0.2512984	total: 1.2s	remaining: 2.77s
303:	learn: 0.2510640	total: 1.21s	remaining: 2.77s
304:	learn: 0.2508058	total: 1.21s	remaining: 2.77s
305:	learn: 0.2505309	total: 1.22s	remaining: 2.77s
306:	learn: 0.2502028	total: 1.23s	remaining: 2.77s
307:	learn: 0.2499188	total: 1.23s	remaining: 2.76s
308:	learn: 0.2496590	total: 1.23s	remaining: 2.75s
309:	learn: 0.2494759	total: 1.24s	remaining: 2.76s
310:	learn: 0.2492493	total: 1.24s	remaining: 2.76s
311:	learn: 0.2491141	total: 1.25s	remaining: 2.76s
312:	learn: 0.2489165	total: 1.25s	remaining: 2.75s
313:	learn: 0.2488383	total: 1.26s	remaining: 2.75s
314:	learn: 0.2486512	total: 1.26s	remaining: 2.75s
315:	learn: 0.2483893	total: 1.27s	remaining: 2.75s
316:	learn: 0.2481206	total: 1.27s	remaining: 2.74s
317:	learn: 0.2477930	total: 1.28s	remaining: 2.74s
318:	learn: 0.2475707	total: 1.28s	remaining: 2.74s
319:	learn: 0.2474232	total: 1.29s	remaining: 2.73s
320:	learn: 0.2472574	total: 1.29s	remaining: 2.73s
321:	learn: 0.2469884	total: 1.3s	remaining: 2.73s
322:	learn: 0.2469047	total: 1.3s	remaining: 2.73s
323:	learn: 0.2465570	total: 1.31s	remaining: 2.73s
324:	learn: 0.2462758	total: 1.31s	remaining: 2.72s
325:	learn: 0.2460697	total: 1.32s	remaining: 2.72s
326:	learn: 0.2458468	total: 1.32s	remaining: 2.72s
327:	learn: 0.2455643	total: 1.32s	remaining: 2.71s
328:	learn: 0.2453225	total: 1.33s	remaining: 2.71s
329:	learn: 0.2449804	total: 1.33s	remaining: 2.71s
330:	learn: 0.2447186	total: 1.34s	remaining: 2.71s
331:	learn: 0.2444266	total: 1.34s	remaining: 2.71s
332:	learn: 0.2442402	total: 1.35s	remaining: 2.7s
333:	learn: 0.2441180	total: 1.35s	remaining: 2.7s
334:	learn: 0.2438009	total: 1.36s	remaining: 2.7s
335:	learn: 0.2436166	total: 1.36s	remaining: 2.69s
336:	learn: 0.2433948	total: 1.37s	remaining: 2.69s
337:	learn: 0.2431686	total: 1.37s	remaining: 2.69s
338:	learn: 0.2429784	total: 1.38s	remaining: 2.69s
339:	learn: 0.2427615	total: 1.39s	remaining: 2.69s
340:	learn: 0.2423762	total: 1.39s	remaining: 2.69s
341:	learn: 0.2421445	total: 1.4s	remaining: 2.69s
342:	learn: 0.2418374	total: 1.4s	remaining: 2.69s
343:	learn: 0.2416238	total: 1.41s	remaining: 2.69s
344:	learn: 0.2414391	total: 1.42s	remaining: 2.69s
345:	learn: 0.2413284	total: 1.42s	remaining: 2.69s
346:	learn: 0.2411484	total: 1.43s	remaining: 2.68s
347:	learn: 0.2408900	total: 1.43s	remaining: 2.69s
348:	learn: 0.2406100	total: 1.44s	remaining: 2.68s
349:	learn: 0.2403227	total: 1.45s	remaining: 2.68s
350:	learn: 0.2401010	total: 1.45s	remaining: 2.68s
351:	learn: 0.2399280	total: 1.45s	remaining: 2.68s
352:	learn: 0.2398396	total: 1.46s	remaining: 2.67s
353:	learn: 0.2397001	total: 1.46s	remaining: 2.67s
354:	learn: 0.2395385	total: 1.47s	remaining: 2.67s
355:	learn: 0.2392986	total: 1.47s	remaining: 2.66s
356:	learn: 0.2391032	total: 1.48s	remaining: 2.66s
357:	learn: 0.2388984	total: 1.48s	remaining: 2.66s
358:	learn: 0.2385905	total: 1.49s	remaining: 2.66s
359:	learn: 0.2383692	total: 1.49s	remaining: 2.65s
360:	learn: 0.2381533	total: 1.5s	remaining: 2.65s
361:	learn: 0.2379455	total: 1.5s	remaining: 2.65s
362:	learn: 0.2375388	total: 1.51s	remaining: 2.65s
363:	learn: 0.2375027	total: 1.51s	remaining: 2.65s
364:	learn: 0.2371951	total: 1.52s	remaining: 2.65s
365:	learn: 0.2369874	total: 1.52s	remaining: 2.64s
366:	learn: 0.2365671	total: 1.53s	remaining: 2.64s
367:	learn: 0.2363996	total: 1.53s	remaining: 2.63s
368:	learn: 0.2362240	total: 1.54s	remaining: 2.63s
369:	learn: 0.2359894	total: 1.54s	remaining: 2.63s
370:	learn: 0.2357676	total: 1.55s	remaining: 2.62s
371:	learn: 0.2353728	total: 1.55s	remaining: 2.62s
372:	learn: 0.2351507	total: 1.56s	remaining: 2.62s
373:	learn: 0.2349571	total: 1.56s	remaining: 2.62s
374:	learn: 0.2348329	total: 1.57s	remaining: 2.62s
375:	learn: 0.2346504	total: 1.58s	remaining: 2.62s
376:	learn: 0.2344062	total: 1.58s	remaining: 2.61s
377:	learn: 0.2342675	total: 1.58s	remaining: 2.61s
378:	learn: 0.2341071	total: 1.59s	remaining: 2.61s
379:	learn: 0.2339114	total: 1.6s	remaining: 2.6s
380:	learn: 0.2337549	total: 1.6s	remaining: 2.6s
381:	learn: 0.2336555	total: 1.6s	remaining: 2.6s
382:	learn: 0.2333943	total: 1.61s	remaining: 2.6s
383:	learn: 0.2331990	total: 1.61s	remaining: 2.59s
384:	learn: 0.2330079	total: 1.62s	remaining: 2.59s
385:	learn: 0.2327446	total: 1.62s	remaining: 2.58s

# Tunnung CatBoost

In [127]:
# Tunning catboost model
pipe.get_params()

{'memory': None,
 'steps': [('columntransformer',
   ColumnTransformer(transformers=[('num',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='median')),
                                                    ('standardscaler',
                                                     StandardScaler())]),
                                    Index(['id', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi'], dtype='object')),
                                   ('cat',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='most_frequent')),
                                                    ('onehotencoder',
                                                     OneHotEncoder(handle_unknown='ignore'))]),
                                    Index(['gender', 'age', 'ever_married', 'work_type', 'Residence_type',
          'smoking_status'],
         dtype='object'))])),
  ('catboostclassifier', CatBoostClassifier(random_state=1))],
 'transform_input': None,
 'verbose': False,
 'columntransformer': ColumnTransformer(transformers=[('num',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='median')),
                                                  ('standardscaler',
                                                   StandardScaler())]),
                                  Index(['id', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi'], dtype='object')),
                                 ('cat',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='most_frequent')),
                                                  ('onehotencoder',
                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                  Index(['gender', 'age', 'ever_married', 'work_type', 'Residence_type',
        'smoking_status'],
       dtype='object'))]),
 'catboostclassifier': CatBoostClassifier(random_state=1),
 'columntransformer__force_int_remainder_cols': True,
 'columntransformer__n_jobs': None,
 'columntransformer__remainder': 'drop',
 'columntransformer__sparse_threshold': 0.3,
 'columntransformer__transformer_weights': None,
 'columntransformer__transformers': [('num',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                   ('standardscaler', StandardScaler())]),
   Index(['id', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi'], dtype='object')),
  ('cat',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                   ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))]),
   Index(['gender', 'age', 'ever_married', 'work_type', 'Residence_type',
          'smoking_status'],
         dtype='object'))],
 'columntransformer__verbose': False,
 'columntransformer__verbose_feature_names_out': True,
 'columntransformer__num': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                 ('standardscaler', StandardScaler())]),
 'columntransformer__cat': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                 ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))]),
 'columntransformer__num__memory': None,
 'columntransformer__num__steps': [('simpleimputer',
   SimpleImputer(strategy='median')),
  ('standardscaler', StandardScaler())],
 'columntransformer__num__transform_input': None,
 'columntransformer__num__verbose': False,
 'columntransformer__num__simpleimputer': SimpleImputer(strategy='median'),
 'columntransformer__num__standardscaler': StandardScaler(),
 'columntransformer__num__simpleimputer__add_indicator': False,
 'columntransformer__num__simpleimputer__copy': True,
 'columntransformer__num__simpleimputer__fill_value': None,
 'columntransformer__num__simpleimputer__keep_empty_features': False,
 'columntransformer__num__simpleimputer__missing_values': nan,
 'columntransformer__num__simpleimputer__strategy': 'median',
 'columntransformer__num__standardscaler__copy': True,
 'columntransformer__num__standardscaler__with_mean': True,
 'columntransformer__num__standardscaler__with_std': True,
 'columntransformer__cat__memory': None,
 'columntransformer__cat__steps': [('simpleimputer',
   SimpleImputer(strategy='most_frequent')),
  ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))],
 'columntransformer__cat__transform_input': None,
 'columntransformer__cat__verbose': False,
 'columntransformer__cat__simpleimputer': SimpleImputer(strategy='most_frequent'),
 'columntransformer__cat__onehotencoder': OneHotEncoder(handle_unknown='ignore'),
 'columntransformer__cat__simpleimputer__add_indicator': False,
 'columntransformer__cat__simpleimputer__copy': True,
 'columntransformer__cat__simpleimputer__fill_value': None,
 'columntransformer__cat__simpleimputer__keep_empty_features': False,
 'columntransformer__cat__simpleimputer__missing_values': nan,
 'columntransformer__cat__simpleimputer__strategy': 'most_frequent',
 'columntransformer__cat__onehotencoder__categories': 'auto',
 'columntransformer__cat__onehotencoder__drop': None,
 'columntransformer__cat__onehotencoder__dtype': numpy.float64,
 'columntransformer__cat__onehotencoder__feature_name_combiner': 'concat',
 'columntransformer__cat__onehotencoder__handle_unknown': 'ignore',
 'columntransformer__cat__onehotencoder__max_categories': None,
 'columntransformer__cat__onehotencoder__min_frequency': None,
 'columntransformer__cat__onehotencoder__sparse_output': True,
 'catboostclassifier__random_state': 1}

In [73]:

# build catboostmodel
cbc = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.1,
    depth=6,
    l2_leaf_reg=2,
    loss_function='Logloss',
    auto_class_weights='Balanced',
    eval_metric='AUC',
    random_seed=1,
    verbose=200
)

pipe=make_pipeline(preprocessor,cbc)

pipe.fit(x_train,y_train)
#evaluate
y_pred=pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",pipe.score(x_train,y_train))
print("accuracy Testing:",pipe.score(x_test,y_test))

0:	total: 2.58ms	remaining: 2.58s
200:	total: 401ms	remaining: 1.59s
400:	total: 769ms	remaining: 1.15s
600:	total: 1.14s	remaining: 758ms
800:	total: 1.53s	remaining: 381ms
999:	total: 1.9s	remaining: 0us
[[240  10]
 [ 31   4]]
              precision    recall  f1-score   support

           0       0.89      0.96      0.92       250
           1       0.29      0.11      0.16        35

    accuracy                           0.86       285
   macro avg       0.59      0.54      0.54       285
weighted avg       0.81      0.86      0.83       285

accuracy Training: 1.0
accuracy Testing: 0.856140350877193

# Smote with Catboost

In [76]:
smote = SMOTE()
cbc = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.1,
    depth=6,
    l2_leaf_reg=2,
    loss_function='Logloss',
    eval_metric='AUC',
    random_seed=1,
    verbose=200
)
cbc_smote_pipe = make_pipeline(preprocessor, smote,cbc)
#Fit and evaluate the model pipeline
cbc_smote_pipe.fit(x_train, y_train)
y_pred=cbc_smote_pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",cbc_smote_pipe.score(x_train,y_train))
print("accuracy Testing:",cbc_smote_pipe.score(x_test,y_test))

0:	total: 18.2ms	remaining: 18.2s
200:	total: 1.95s	remaining: 7.74s
400:	total: 5.24s	remaining: 7.82s
600:	total: 7.41s	remaining: 4.92s
800:	total: 8.82s	remaining: 2.19s
999:	total: 11.2s	remaining: 0us
[[242   8]
 [ 29   6]]
              precision    recall  f1-score   support

           0       0.89      0.97      0.93       250
           1       0.43      0.17      0.24        35

    accuracy                           0.87       285
   macro avg       0.66      0.57      0.59       285
weighted avg       0.84      0.87      0.84       285

accuracy Training: 1.0
accuracy Testing: 0.8701754385964913

In [96]:
smote = SMOTE()
cbc = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.1,
    depth=6,
    l2_leaf_reg=1050,
    loss_function='Logloss',
    eval_metric='AUC',
    random_seed=1,
    verbose=200
)
cbc_smote_pipe = make_pipeline(preprocessor, smote,cbc)
#Fit and evaluate the model pipeline
cbc_smote_pipe.fit(x_train, y_train)
y_pred=cbc_smote_pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",cbc_smote_pipe.score(x_train,y_train))
print("accuracy Testing:",cbc_smote_pipe.score(x_test,y_test))

0:	total: 16.5ms	remaining: 16.5s
200:	total: 2.9s	remaining: 11.5s
400:	total: 6.84s	remaining: 10.2s
600:	total: 10.7s	remaining: 7.11s
800:	total: 13.2s	remaining: 3.27s
999:	total: 14.2s	remaining: 0us
[[238  12]
 [ 32   3]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.92       250
           1       0.20      0.09      0.12        35

    accuracy                           0.85       285
   macro avg       0.54      0.52      0.52       285
weighted avg       0.80      0.85      0.82       285

accuracy Training: 0.9143192488262911
accuracy Testing: 0.8456140350877193

In [138]:
smote = SMOTE()
cbc = CatBoostClassifier(verbose=200,
    l2_leaf_reg=200, eval_metric='AUC',)
cbc_smote_pipe = make_pipeline(preprocessor, smote,cbc)
#Fit and evaluate the model pipeline
cbc_smote_pipe.fit(x_train, y_train)
y_pred=cbc_smote_pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",cbc_smote_pipe.score(x_train,y_train))
print("accuracy Testing:",cbc_smote_pipe.score(x_test,y_test))

0:	total: 20.5ms	remaining: 20.5s
200:	total: 2.73s	remaining: 10.9s
400:	total: 4.86s	remaining: 7.26s
600:	total: 7.69s	remaining: 5.11s
800:	total: 9.76s	remaining: 2.42s
999:	total: 11.6s	remaining: 0us
[[240  10]
 [ 29   6]]
              precision    recall  f1-score   support

           0       0.89      0.96      0.92       250
           1       0.38      0.17      0.24        35

    accuracy                           0.86       285
   macro avg       0.63      0.57      0.58       285
weighted avg       0.83      0.86      0.84       285

accuracy Training: 0.9248826291079812
accuracy Testing: 0.8631578947368421

## smotw with cbc (defult parameter)

In [120]:
smote = SMOTE()
cbc = CatBoostClassifier(verbose=200)
cbc_smote_pipe = make_pipeline(preprocessor, smote,cbc)
#Fit and evaluate the model pipeline
cbc_smote_pipe.fit(x_train, y_train)
y_pred=cbc_smote_pipe.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("accuracy Training:",cbc_smote_pipe.score(x_train,y_train))
print("accuracy Testing:",cbc_smote_pipe.score(x_test,y_test))

Learning rate set to 0.01225
0:	learn: 0.6857026	total: 19.6ms	remaining: 19.6s
200:	learn: 0.2643368	total: 2.6s	remaining: 10.3s
400:	learn: 0.1879282	total: 3.63s	remaining: 5.42s
600:	learn: 0.1455497	total: 4.66s	remaining: 3.1s
800:	learn: 0.1161794	total: 5.69s	remaining: 1.41s
999:	learn: 0.0937200	total: 6.7s	remaining: 0us
[[242   8]
 [ 30   5]]
              precision    recall  f1-score   support

           0       0.89      0.97      0.93       250
           1       0.38      0.14      0.21        35

    accuracy                           0.87       285
   macro avg       0.64      0.56      0.57       285
weighted avg       0.83      0.87      0.84       285

accuracy Training: 0.9812206572769953
accuracy Testing: 0.8666666666666667